### PR TITLE
coordinated shutdown

### LINKED ISSUE #1425: Implement akka CoordinatedShutdown
While reviewing the code, I noticed there are places that just `System.exit` which might cause some DB corruptions. I have good experience with akka's CoordinatedShutdown which is great for closing resources on shutdown etc.

Also all actors should have supervision strategy to log exceptions that are thrown from the Actor thread.

### PR DESCRIPTION
**Pull request by pragmaxim**
Closes #1425  ... tests fail because it depends on newest scorex

### CODE REVIEW

File: src/main/scala/org/ergoplatform/ErgoApp.scala [hunk 1]
```diff
@@ -166,28 +165,7 @@ class ErgoApp(args: Args) extends ScorexLogging {
...
 
     Http().newServerAt(bindAddress.getAddress.getHostAddress, bindAddress.getPort).bindFlow(httpService.compositeRoute)
-
-    //on unexpected shutdown
-    Runtime.getRuntime.addShutdownHook(new Thread() {
-      override def run() {
-        log.error("Unexpected shutdown")
-        stopAll()
-      }
-    })
```
Comment (aslesarenko) [inline src/main/scala/org/ergoplatform/ErgoApp.scala:176]: Why this hook is not necessary?

Comment (pragmaxim) [reply src/main/scala/org/ergoplatform/ErgoApp.scala:176]: I ported it to a CoordinatedShutdown task which is triggered on this hook implicitly ... One would have to explicitly disable it : 
```
akka.coordinated-shutdown.run-by-jvm-shutdown-hook=off
```

**Comment by kushti** [comment]
@pragmaxim please add ScalaDoc for new (or touched) classes and methods, and add comments to the new code

**Review by kushti — APPROVED** [review]
