### PR TITLE
Uniquely name docker resources and clean up on integration tests start

### LINKED ISSUE #270: Integration tests must clean up builded docker images at the tests end
```
# docker image ls
<none>                           <none>              7c0d1b536d2c        29 hours ago        177MB
<none>                           <none>              db123410c002        31 hours ago        177MB
<none>                           <none>              28fd0ee02762        2 days ago          177MB
<none>                           <none>              2ad53f2d8797        2 days ago          177MB
<none>                           <none>              63136623fb3a        4 days ago          177MB
<none>                           <none>              95101d35d3d7        4 days ago          177MB
<none>                           <none>              64dccf1542cf        4 days ago          177MB
<none>                           <none>              d2b8c8270b5c        4 days ago          177MB
<none>                           <none>              c760374130ed        4 days ago          177MB
<none>                           <none>              e8a99f9108a3        4 days ago          177MB
<none>                           <none>              24a4893061df        4 days ago          177MB
<none>                           <none>              5acfc23118c0        4 days ago          177MB
<none>                           <none>              d6db23d122a9        5 days ago          177MB
<none>                           <none>              deb2dfbea1a3        5 days ago          177MB
<none>                           <none>              1da923d6123f        5 days ago          177MB
<none>                           <none>              6bf82cfafb55        5 days ago          177MB
<none>                           <none>              0458cf7a2edc        11 days ago         177MB
<none>                           <none>              895937b912a9        11 days ago         177MB
<none>                           <none>              b8e1514cd324        11 days ago         177MB
<none>                           <none>              50ba2f429640        12 days ago         177MB
<none>                           <none>              d9b75098a8bf        12 days ago         177MB
<none>                           <none>              c8003b20c563        12 days ago         177MB
...
```

This should be deleted by the tests I guess...

### LINKED ISSUE #278: Integration tests. Uniquely name docker resources and clean up on start.
Following our discussion with @mike-aksarin :

Problem.
Running tests for the second time after a crash fails due to docker resources (containers, network) being re-used which is not intended(container name conflicts, network subnet != container.ip, etc.).

Solution
- use unique names for containers and network with `ergo-itest-` prefix;
- delete existing `ergo-itest-*` containers and network on test suite launch;

Note: In case of simultaneously running tests we can further isolate them by including commit hash/branch name/etc. in the name prefix.

### PR DESCRIPTION
**Pull request by greenhat**
Closes #278 
Closes #270

### CODE REVIEW

File: src/it/scala/org/ergoplatform/it/TestFourNodesSuite.scala [hunk 1]
```diff
@@ -16,7 +16,10 @@ class TestFourNodesSuite extends FreeSpec with BeforeAndAfterAll with ScorexLogg
     """.stripMargin
   )
 
-  private val docker = Docker(getClass)
+  private val docker: Docker = {
+    Docker.cleanupResourcesIfNeeded()
```
Comment (mike-aksarin) [inline src/it/scala/org/ergoplatform/it/TestFourNodesSuite.scala]: I thing it worth moving this call to `docker.close` and move the `cleanupResourcesIfNeeded method`  to `Docker` class, not an object

File: src/it/scala/org/ergoplatform/it/Docker.scala [hunk 2]
```diff
@@ -296,5 +299,29 @@ object Docker {
...
+      .filter(_.names.asScala.head.startsWith("/" + networkNamePrefix))
+      .foreach(c => client.removeContainer(c.id, RemoveContainerParam.forceKill))
+    // removes networks
+    client.listNetworks(ListNetworksParam.customNetworks).asScala
+      .filter(_.name().startsWith(networkNamePrefix))
+      .foreach(n => client.removeNetwork(n.id))
+  }
+
+  def cleanupResourcesIfNeeded(): Unit =
+    Try { Docker.NodeConfigs.getBoolean("testing.integration.cleanupDocker") }
```
Comment (mike-aksarin) [inline src/it/scala/org/ergoplatform/it/Docker.scala]: It's better to use `ficus` here as we do at the project:
```
import net.ceedubs.ficus.Ficus._
```
and then:

```
val shouldCleanup = Docker.NodeConfigs.getOrElse[Boolean]("testing.integration.cleanupDocker", false)
```

Comment (greenhat) [reply src/it/scala/org/ergoplatform/it/Docker.scala]: Nice catch. I missed that. Thanks.

File: src/it/scala/org/ergoplatform/it/TestFourNodesSuite.scala (hunk 1 above)
Comment (mike-aksarin) [reply src/it/scala/org/ergoplatform/it/TestFourNodesSuite.scala]: Make sense. I'll move the `cleanupResourcesIfNeeded ` call to `startNodes`  then

Comment (greenhat) [reply src/it/scala/org/ergoplatform/it/TestFourNodesSuite.scala]: It'll be too late. We create docker network in `Docker.innerNetwork` on instantiation.

Comment (mike-aksarin) [reply src/it/scala/org/ergoplatform/it/TestFourNodesSuite.scala]: oh, indeed! Then I'll but it to initialization section just after client creation

**Comment by mike-aksarin** [comment]
Also closes  #270 now

File: build.sbt [hunk 3]
```diff
@@ -115,6 +115,7 @@ dockerfile in docker := {
 
   new Dockerfile {
     from("anapsix/alpine-java:8_server-jre")
+    label("ergo", "ergo")
```
Comment (greenhat) [inline build.sbt]: I suppose this image is made exclusively for integration tests (we have `Dockerfile` in the root folder). I suggest we make the label more specific (e.g. "ergo-integration-tests"). Otherwise, we risk deleting wrong images since such label can be used in the future for other types of images (demo, experiments, etc.).

Comment (mike-aksarin) [reply build.sbt]: it's never used, but ok, let's use `ergo-integration-tests`
