### PR TITLE
Catch possible null from getAddress

### LINKED ISSUE #1739: PeerSpecSerializer.serialize can fail with NPE
```
21:54:55.885 INFO  [tor.default-dispatcher-12] s.c.n.NetworkController - Unconfirmed connection: (/109.167.229.52:39520, /10.10.2.4:9030) => ConnectionId(remote=/109.167.229.52:39520, local=/10.10.2.4:9030, direction=Incoming)
21:54:55.885 INFO  [tor.default-dispatcher-12] s.c.n.peer.PeerManager - Connection confirmation request: ConnectionId(remote=/109.167.229.52:39520, local=/10.10.2.4:9030, direction=Incoming)
21:54:55.885 INFO  [tor.default-dispatcher-12] s.c.n.NetworkController - Connection confirmed to ConnectionId(remote=/109.167.229.52:39520, local=/10.10.2.4:9030, direction=Incoming)
21:54:55.885 INFO  [tor.default-dispatcher-12] s.c.n.NetworkController - New incoming connection from /109.167.229.52:39520 established (bound to local /10.10.2.4:9030)
21:54:55.886 WARN  [tor.default-dispatcher-12] s.c.n.NetworkController - Stopping child actor failed with: {}
akka.actor.ActorInitializationException: akka://ergoref/user/networkController/$cB: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:661)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException: null
	at scorex.core.network.PeerSpecSerializer.$anonfun$serialize$1(PeerSpec.scala:48)
	at scorex.core.network.PeerSpecSerializer.$anonfun$serialize$1$adapted(PeerSpec.scala:47)
	at scorex.util.serialization.VLQWriter.putOption(VLQWriter.scala:143)
	at scorex.util.serialization.VLQWriter.putOption$(VLQWriter.scala:139)
	at scorex.util.serialization.VLQByteBufferWriter.putOption(VLQByteBufferWriter.scala:9)
	at scorex.util.serialization.VLQByteBufferWriter.putOption(VLQByteBufferWriter.scala:9)
	at scorex.core.network.PeerSpecSerializer.serialize(PeerSpec.scala:47)
	at scorex.core.network.message.HandshakeSpec.serialize(BasicMessagesRepo.scala:267)
	at scorex.core.network.message.HandshakeSpec.serialize(BasicMessagesRepo.scala:252)
	at scorex.core.serialization.ScorexSerializer.toBytes(ScorexSerializer.scala:30)
	at scorex.core.serialization.ScorexSerializer.toBytes$(ScorexSerializer.scala:28)
	at scorex.core.network.message.HandshakeSpec.toBytes(BasicMessagesRepo.scala:252)
	at scorex.core.network.PeerConnectionHandler.handshaking(PeerConnectionHandler.scala:71)
	at scorex.core.network.PeerConnectionHandler.preStart(PeerConnectionHandler.scala:61)
	at akka.actor.Actor.aroundPreStart(Actor.scala:548)
```

### PR DESCRIPTION
**Pull request by jellymlg**
closes #1739

### CODE REVIEW

File: src/main/scala/scorex/core/network/PeerSpec.scala [hunk 1]
```diff
@@ -45,7 +45,7 @@ class PeerSpecSerializer(featureSerializers: PeerFeature.Serializers) extends Sc
 
 
     w.putOption(obj.declaredAddress) { (writer, isa) =>
-      val addr = isa.getAddress.getAddress
+      val addr = if(isa.getAddress == null) Array.fill[Byte](4){0} else isa.getAddress.getAddress
```
Comment (kushti) [inline src/main/scala/scorex/core/network/PeerSpec.scala:48]: Why to write 0s ? I guess it is safer to write None in putOption (thus trying to decode address before putOption)

**Review by kushti — CHANGES_REQUESTED** [review]

File: src/main/scala/scorex/core/network/PeerSpec.scala (hunk 1 above)
Comment (kushti) [reply src/main/scala/scorex/core/network/PeerSpec.scala]: @jellymlg looks good now. Any known test vectors for getting null in address to make a test for this case ?

Comment (jellymlg) [reply src/main/scala/scorex/core/network/PeerSpec.scala]: > @jellymlg looks good now. Any known test vectors for getting null in address to make a test for this case ?

From what I can tell, this can happen when the connecting peer is running in the cloud and has an unresolveable declaredAddress (just an idea)

**Review by kushti — APPROVED** [review]
