### PR TITLE
Fix todos

### LINKED ISSUE #316: Fix code TODOs

### PR DESCRIPTION
**Pull request by catena2w**
close #316

### CODE REVIEW

File: src/main/scala/org/ergoplatform/local/TransactionGenerator.scala [hunk 1]
```diff
@@ -46,10 +46,8 @@ class TransactionGenerator(viewHolder: ActorRef, settings: TestingSettings) exte
         }
       }*/
 
-    case txs: Seq[ErgoTransaction] =>
-      txs.foreach { tx =>
+    case tx: ErgoTransaction =>
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/local/TransactionGenerator.scala]: What is the reason to make this change for the class which is not working (and not sending to self neither an instance of ErgoTransaction nor Seq[ErgoTransaction] ?

File: src/main/scala/org/ergoplatform/modifiers/history/Header.scala [hunk 2]
```diff
@@ -37,9 +37,8 @@ case class Header(version: Version,
 
   override lazy val id: ModifierId = ModifierId @@ powHash
 
-  //todo: why SHA256?
-  //todo: tolsi: check this
   lazy val powHash: Digest32 = {
+    // implementations of pow hash similar to ZCash.
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/modifiers/history/Header.scala]: An implementation of a PoW function which is similar to one used in ZCash.

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+import com.google.common.primitives.{Bytes, Shorts}
+import org.ergoplatform.modifiers.history.{Header, HeaderSerializer}
+import org.ergoplatform.settings.Constants
+import scorex.core.serialization.{BytesSerializable, Serializer}
+import scorex.crypto.authds.ADDigest
+
+import scala.util.Try
+
+/**
+  * Additional data, required for transactions validation.
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: Additional data required for transactions validation

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+  *
+  * @param lastHeaders - fixed number of last applied header
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: fixed number of last applied block headers

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+  * @param digest      - AVL tree root hash state BEFORE current block application
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: An AVL tree root hash of the UTXO state BEFORE current block application

File: src/main/scala/org/ergoplatform/settings/Constants.scala [hunk 6]
```diff
@@ -11,4 +11,5 @@ object Constants {
   val InitialNBits: Long = RequiredDifficulty.encodeCompactBits(InitialDifficulty)
   val ModifierIdSize: Int = hashLength
   val MaxTransactionCost: Long = 1000000    //todo: move to config
+  val LastHeadersAvailableForTxValidation: Int = 10
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/settings/Constants.scala]: Where did you get this number?

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+  */
+case class ErgoStateContext(lastHeaders: Seq[Header], digest: ADDigest) extends BytesSerializable {
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: I think this class and corresponding changes in the codebase should be moved into a separate PR, they have nothing to do with fixing todos.

File: src/main/resources/application.conf [hunk 8]
```diff
@@ -31,6 +31,9 @@ ergo {
 
     # Delay for miner after succesful block creation
     miningDelay = 5s
+
+    # Number of State snapshots to keep. Defines maximum rollback depth
```
[the remark this answers is not in the document]
Comment (catena2w) [reply src/main/resources/application.conf]: +

File: src/main/scala/org/ergoplatform/local/TransactionGenerator.scala (hunk 1 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/local/TransactionGenerator.scala]: This string generated a warning due to "type pattern is unchecked since it is eliminated by erasure" and required to be fixed. I may just remove this string, it's hard to fix correctly, because class is not implemented

File: src/main/scala/org/ergoplatform/modifiers/history/Header.scala (hunk 2 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/modifiers/history/Header.scala]: fixed

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala (hunk 3 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: fixed

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala (hunk 4 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: replaced to height

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala (hunk 7 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: fixed

File: src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala (hunk 5 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala]: fixde

File: src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala [hunk 9]
```diff
@@ -31,29 +29,34 @@ trait UtxoStateReader extends ErgoStateReader with ScorexLogging with Transactio
...
+          boxById(id)
+      }
+    case None =>
+      log.debug("No emission box: emission should be already finished before this block")
+      None
   }
 
-  // TODO implement
-  def stateContext(): ErgoStateContext = ErgoStateContext(0, rootHash)
+  protected def getEmissionBoxId(): Option[ADKey] = store.get(ByteArrayWrapper(UtxoState.EmissionBoxIdKey))
```
[the remark this answers is not in the document]
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala]: fixed

File: src/main/scala/org/ergoplatform/settings/Constants.scala (hunk 6 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/settings/Constants.scala]: removed

File: src/main/scala/org/ergoplatform/settings/ErgoSettings.scala [hunk 10]
```diff
@@ -52,25 +52,37 @@ object ErgoSettings extends ScorexLogging
...
+      failWithError("Can not use UTXO state when nodeSettings.verifyTransactions is false")
+    } else {
+      settings
+    }
+  }
+
+  private def failWithError(msg: String): Nothing = {
+    log.error(s"Stop application due to malformed configuration file: $msg")
+    ErgoApp.forceStopApplication()
+    ???
```
[the remark this answers is not in the document]
Comment (catena2w) [reply src/main/scala/org/ergoplatform/settings/ErgoSettings.scala]: fixed

File: src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/HeadersProcessor.scala [hunk 11]
```diff
@@ -34,9 +34,6 @@ trait HeadersProcessor extends ToDownloadProcessor with ScorexLogging with Score
 
   val powScheme: PowScheme
 
-  //TODO alternative DDoS protection
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/HeadersProcessor.scala]: The removed todo should be moved to a place around "keepVersions" field I guess.

File: src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/popow/PoPoWProofsProcessor.scala [hunk 12]
```diff
@@ -23,6 +23,7 @@ trait PoPoWProofsProcessor extends HeadersProcessor with ScorexLogging {
 
   /**
     * Constructs SPV Proof from KLS16 paper
+    * TODO replace to NiPoPoW
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/popow/PoPoWProofsProcessor.scala]: "TODO: replace with KMZ17" (or NiPoPoW)

File: src/main/scala/org/ergoplatform/nodeView/state/DigestState.scala [hunk 13]
```diff
@@ -126,9 +125,21 @@ class DigestState protected(override val version: VersionTag,
 
   def close(): Unit = store.close()
 
-  private def update(newVersion: VersionTag, newRootHash: ADDigest): Try[DigestState] = Try {
+  private def update(header: Header): Try[DigestState] = {
+    val version: VersionTag = VersionTag @@ header.id
+    val newContext = stateContext.appendHeader(header)
+    val cb = ByteArrayWrapper(ErgoStateReader.ContextKey) -> ByteArrayWrapper(newContext.bytes)
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/state/DigestState.scala]: Why to store the state context on disk on every header, if we can trivially get it from history during startup (e.g. in ErgoNodeViewHolder), and then hold it in memory only?

File: src/main/scala/org/ergoplatform/nodeView/state/UtxoState.scala [hunk 14]
```diff
@@ -146,44 +143,44 @@ class UtxoState(override val version: VersionTag,
...
+    val eb = EmissionBoxIdKey -> currentEmissionBoxOpt.map(emissionBox => emissionBox.id).getOrElse(Array[Byte]())
+    val cb = ErgoStateReader.ContextKey -> context.bytes
 
-    Seq(idStateDigestIdxElem, stateDigestIdIdxElem, bestVersion, eb)
+    Seq(idStateDigestIdxElem, stateDigestIdIdxElem, bestVersion, eb, cb)
   }
 
-  def create(dir: File, emission: CoinsEmission, nodeViewHolderRef: Option[ActorRef]): UtxoState = {
-    val store = new LSMStore(dir, keepVersions = ErgoState.KeepVersions)
+  def create(dir: File, constants: StateConstants): UtxoState = {
```
Comment (kushti) [inline src/main/scala/org/ergoplatform/nodeView/state/UtxoState.scala]: Why not to move storage folder to StateConstants as well?

File: src/test/scala/org/ergoplatform/nodeView/WrappedUtxoState.scala [hunk 15]
```diff
@@ -38,7 +35,9 @@ class WrappedUtxoState(override val version: VersionTag,
   override def applyModifier(mod: ErgoPersistentModifier): Try[WrappedUtxoState] = super.applyModifier(mod) match {
     case Success(us) =>
       mod match {
-        case ct: TCPMOD =>
+        case ct: TransactionsCarryingPersistentNodeViewModifier[ErgoTransaction@unchecked]
+          if ct.transactions.forall(_.isInstanceOf[ErgoTransaction]) =>
```
Comment (kushti) [inline src/test/scala/org/ergoplatform/nodeView/WrappedUtxoState.scala]: Why to perform this check? You can not get block with transactions not being of ErgoTransaction type.

File: src/test/scala/org/ergoplatform/nodeView/state/ErgoStateSpecification.scala [hunk 16]
```diff
@@ -1,14 +1,29 @@
...
+import org.ergoplatform.modifiers.history.Header
 import org.ergoplatform.settings.ErgoSettings
 import org.ergoplatform.utils.ErgoPropertyTest
 
 import scala.util.Random
 
-
 class ErgoStateSpecification extends ErgoPropertyTest {
 
+  property("stateContext should be the same for Utxo and Diget states") {
```
Comment (kushti) [inline src/test/scala/org/ergoplatform/nodeView/state/ErgoStateSpecification.scala]: Diget => Digest

File: src/main/scala/org/ergoplatform/nodeView/state/DigestState.scala (hunk 13 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/DigestState.scala]: Unfortunately we can not keep them just in memory, because in addition to startup, we should also recover it on rollback, and `rollbackTo` method only contains `version`, we can not recover height (and other possibly required fields) if we do not keep them in the same DB we rollback.

File: src/main/scala/org/ergoplatform/nodeView/state/UtxoState.scala (hunk 14 above)
Comment (catena2w) [reply src/main/scala/org/ergoplatform/nodeView/state/UtxoState.scala]: Because we do not need it inside a state, `StateConstants` just keeps fields, required for state, that do not change with the time.
