### PR TITLE
Integration tests fix

### LINKED ISSUE #653: Fix known peers propagation test

### PR DESCRIPTION
**Pull request by ccellado**
Closes #653 #1564 #1160

- New Docker library used
- DeepRollBack spec changed
- WalletSpec changed
- Works without sudo, if you cannot run without sudo, please check your local settings / owner of the .docker folder
- OpenApiSpec ignored since Docker image for it removed from registry, will create another issue
- Added it tests to GithubActions

### CODE REVIEW

File: src/it/scala/org/ergoplatform/it/api/NodeApi.scala [hunk 1]
```diff
@@ -130,13 +130,17 @@ trait NodeApi {
                interval: FiniteDuration = 1.second,
                statusCode: Int = HttpConstants.ResponseStatusCodes.OK_200): Future[Response] = {
     def executeRequest: Future[Response] = {
+//      log.info(s"Executing request '$request'")
       log.trace(s"Executing request '$request'")
       client.executeRequest(request, new AsyncCompletionHandler[Response] {
         override def onCompleted(response: Response): Response = {
           if (response.getStatusCode == statusCode) {
+//            log.info(s"Request: ${request.getUrl} \n Response: ${response.getResponseBody}")
```
Comment (kushti) [inline src/it/scala/org/ergoplatform/it/api/NodeApi.scala:138]: Please avoid commented out code.

File: src/it/scala/org/ergoplatform/it/api/NodeApi.scala [hunk 2]
```diff
@@ -130,13 +130,17 @@ trait NodeApi {
...
             log.debug(s"Request: ${request.getUrl} \n Response: ${response.getResponseBody}")
             response
           } else {
+//            log.info(s"Request:  ${request.getUrl} \n Unexpected status code(${response.getStatusCode}): " +
```
Comment (kushti) [inline src/it/scala/org/ergoplatform/it/api/NodeApi.scala:142]: Please avoid commented out code.

File: src/it/scala/org/ergoplatform/it/api/NodeApi.scala [hunk 3]
```diff
@@ -145,6 +149,7 @@ trait NodeApi {
       }).toCompletableFuture.toScala
         .recoverWith {
           case e@(_: IOException | _: TimeoutException) =>
+//            log.info(s"Failed to execute request '$request' with error: ${e.getMessage}")
```
Comment (kushti) [inline src/it/scala/org/ergoplatform/it/api/NodeApi.scala:152]: Please avoid commented out code.

**Review by kushti — APPROVED** [review]
