### PR TITLE
Shutdown hook has been added to prevent corrupted state after restart

### LINKED ISSUE #155: Application shutdown
Check that node shutdown correctly. For now it throws an Exception, not sure that it closes in consistent state

### PR DESCRIPTION
**Pull request by daron666**
fixes #155

### CODE REVIEW

File: src/main/scala/org/ergoplatform/ErgoApp.scala [hunk 1]
```diff
@@ -65,15 +67,30 @@ class ErgoApp(args: Seq[String]) extends Application {
...
 
+  val actorsToStop = Seq(minerRef,
+    peerManagerRef,
+    networkControllerRef,
+    readersHolderRef,
+    nodeViewSynchronizer,
+    localInterface,
+    nodeViewHolderRef
+  )
+  sys.addShutdownHook(ErgoApp.shutdown(actorSystem, actorsToStop))
```
Comment (mike-aksarin) [inline src/main/scala/org/ergoplatform/ErgoApp.scala]: I think we also need to ensure that shutdown procedure is correct for the node terminations due to unhandled exceptions, e.g. in Actor threads. Coordinated shutdown occurs in this case, but I'm not sure that we close all the actors gracefully.

**Comment by mike-aksarin** [comment]
Looks great! Maybe we could  also ensure that shutdown procedure is correct as well for the node terminations due to *unhandled exceptions*, e.g. in Actor threads? Coordinated shutdown occurs in this case, but I'm not sure that we close all the actors gracefully.
